name: mswin
on:
  push:
    branches:
      - '*'
#  schedule:
#    - cron: '50 1,8,15 * * *'
  workflow_dispatch:

jobs:
  mswin:
    strategy:
      matrix:
        vs: [2022]
      fail-fast: false
    runs-on: windows-${{ matrix.vs }}
    env:
      APPVEYOR: 'True'

    steps:
      - name: git config
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: repo checkout
        uses: actions/checkout@v3

      - name: Checkout ruby
        run: |
          $gh = 'https://github.com'
          git clone -q --depth=1 --no-tags --branch=master $gh/ruby/ruby.git src

      - name: load ruby
        timeout-minutes: 30
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: mswin
          vcpkg: gmp

      - name: Cache - .downloaded-cache
        uses: actions/cache@v3
        with:
          path: .downloaded-cache
          key: dl-cache-win-mswin-${{ hashFiles('src/gems/bundled_gems') }}

      - name: Configure
        shell: cmd
        run: |
          mkdir .downloaded-cache
          mklink /j %cd%\src\.downloaded-cache %cd%\.downloaded-cache
          mkdir install
          mkdir install
          set PRE=%cd%\ruby-mswin
          mkdir build
          cd build
          ../src/win32/configure.bat --disable-install-doc --prefix=%PRE% --without-ext=+,dbm,gdbm --with-opt-dir=C:/vcpkg/installed/x64-windows --so-name=x64-ucrt-ruby320

#      - name: ssl cert.pem
#        run: |
#          # copy current cert file to mswin location
#          curl -fsSL -o ruby-ucrt.7z --retry 10 https://github.com/MSP-Greg/ruby-loco/releases/download/ruby-master/ruby-ucrt.7z
#          &"C:\Program Files\7-zip\7z.exe" e ruby-ucrt.7z -ossl ruby-ucrt/ssl/cert.pem
#          Copy-Item .\ssl\cert.pem "C:\Program Files\Common Files\SSL\cert.pem"
#          Copy-Item .\ssl\cert.pem "$env:VCPKG_INSTALLATION_ROOT\packages\openssl_x64-windows\cert.pem"
#          cd build

      - name: apply patches
        run: |
          cd src
          patch.exe -p1 -N --no-backup-if-mismatch -i ../mswin_patches/test-all.patch
          patch.exe -p1 -N --no-backup-if-mismatch -i ../mswin_patches/test-all_open_port.patch
      - name: nmake
        timeout-minutes: 20
        run:  |
          cd build
          nmake

      - name: nmake install
        run: |
          $env:Path = "C:\vcpkg\installed\x64-windows\bin;$env:Path"
          cd build
          nmake "DESTDIR=" install-nodoc

      - name: misc install, ruby -v
        run: |
          $repo = $pwd
          del ruby-mswin\lib\x64-ucrt-ruby320-static.lib
          mkdir ruby-mswin\bin\ruby_builtin_dlls 2>&1>$null
          mkdir ruby-mswin\ssl                   2>&1>$null
          cd ruby-mswin\bin\ruby_builtin_dlls
          Copy-Item C:\vcpkg\installed\x64-windows\bin\libcrypto-3-x64.dll
          Copy-Item C:\vcpkg\installed\x64-windows\bin\libssl-3-x64.dll
          Copy-Item C:\vcpkg\installed\x64-windows\bin\gmp-10.dll
          Copy-Item C:\vcpkg\installed\x64-windows\bin\gmpxx-4.dll
          Copy-Item C:\vcpkg\installed\x64-windows\bin\libffi.dll
          Copy-Item C:\vcpkg\installed\x64-windows\bin\yaml.dll
          Copy-Item C:\vcpkg\installed\x64-windows\bin\readline.dll
          Copy-Item C:\vcpkg\installed\x64-windows\bin\zlib1.dll
          Copy-Item $repo\mswin\ruby_builtin_dlls.manifest
          cd ..
          mt.exe -manifest $repo\mswin\ruby-exe.xml -outputresource:ruby.exe;1
          mt.exe -manifest $repo\mswin\ruby-exe.xml -outputresource:rubyw.exe;1
          cd $repo
          Copy-Item .\ssl\cert.pem ruby-mswin\ssl\cert.pem
          Copy-Item "$env:VCPKG_INSTALLATION_ROOT\packages\openssl_x64-windows\openssl.cnf" ruby-mswin\ssl\openssl.cnf
          $env:Path = "$repo\ruby-mswin\bin;$repo\ruby-mswin\bin\ruby_builtin_dlls;$env:Path"
          ruby-mswin/bin/ruby.exe -v mswin/copy_bash_scripts.rb

      - name: nmake test
        timeout-minutes: 4
        shell: cmd
        run: |
          cd build
          set PATH=%cd%\ruby-mswin\bin;%cd%\ruby-mswin\bin\ruby_builtin_dlls;%PATH%
          set BUNDLER_VERSION=
          nmake test

      # copy dll files to bin folder, add bin to path
      # ruby/test_time_tz.rb requires additional gems
      - name: nmake test-all -j
        timeout-minutes: 40
        shell: cmd
        run: |
          set /a JOBS=%NUMBER_OF_PROCESSORS%
          set EXCL_N=--exclude test_mjit --exclude test_syntax --exclude test_time_tz --exclude test_undef  --exclude test_objspace
          chcp 437
          set PATH=%cd%\ruby-mswin\bin;%cd%\ruby-mswin\bin\ruby_builtin_dlls;%PATH%
          set BUNDLER_VERSION=
          cd build
          nmake test-all "TESTOPTS=-j%JOBS% %EXCL_N% -v --timeout-scale=3.0 --retry --job-status=normal --show-skip"

      - name: nmake test-all singles
        timeout-minutes: 5
        shell: cmd
        run: |
          set tr=../src/test/ruby
          set TESTS=%tr%/test_mjit.rb ../src/test/objspace/test_objspace.rb %tr%/test_syntax.rb %tr%/test_time_tz.rb %tr%/test_undef.rb
          chcp 437
          set PATH=%cd%\ruby-mswin\bin;%cd%\ruby-mswin\bin\ruby_builtin_dlls;%PATH%
          set BUNDLER_VERSION=
          cd build
          nmake test-all "TESTOPTS=-v --timeout-scale=3.0"

      - name: test-spec from install
        timeout-minutes: 6
        shell: cmd
        run: |
          chcp 437
          set PATH=%cd%\ruby-mswin\bin;%PATH%
          set BUNDLER_VERSION=
          cd src/spec/ruby
          ruby ../mspec/bin/mspec -j -I../../tool/lib

      - name: CLI Check
        run: ./mswin/cli_test.ps1

      - name: copy misc files
        run: |
          cd ruby-mswin
          Copy-Item ../src/BSDL
          Copy-Item ../src/COPYING
          Copy-Item ../src/LEGAL
          $arch = $(./bin/ruby -e "STDOUT.write RbConfig::CONFIG['archdir']")
          Rename-Item -Path $arch/readline.so -NewName $arch/readline.so_

      - name: upload asset
        timeout-minutes: 5
        uses: ./.github/actions/upload-binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ruby_path: ./ruby-mswin
