name: mswin
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  mswin:
    strategy:
      matrix:
        vs: [2025]
      fail-fast: false
    runs-on: windows-${{ matrix.vs }}
    env:
      PRE: ruby-mswin

    steps:
      - name: git config
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: repo checkout
        uses: actions/checkout@v4

      - name: Update VS Build Tools
        run: ./UpdateVS.ps1 -RunAsAdmin

      - name: Run vs_installer.exe
        run: |
          Start-Process -Wait -FilePath  "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList "update --quiet --norestart --installpath ""C:\Program Files\Microsoft Visual Studio\2022\Enterprise"""

      - name: VS Where
        run: |
          &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
