name: mswin
on:
  push:
    branches:
      - '*'
#  schedule:
#    - cron: '50 1,8,15 * * *'
  workflow_dispatch:

jobs:
  mswin:
    strategy:
      matrix:
        vs: [2022]
      fail-fast: false
    runs-on: windows-${{ matrix.vs }}
    env:
      APPVEYOR: 'True'
      RL_DIR: ruby-mswin

    steps:
      - name: git config
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: repo checkout
        uses: actions/checkout@v3

      - name: get ruby and rubyinstaller2
        timeout-minutes: 5
        run: |
          $gh = 'https://github.com'
          git clone -q --depth=1 --no-tags --branch=master  $gh/oneclick/rubyinstaller2.git ./rubyinstaller2
          git clone -q --depth=1 --no-tags --branch=master  $gh/ruby/ruby.git               ./ruby

      - name: load ruby
        timeout-minutes: 12
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: mswin

      - name: Cache - .downloaded-cache
        uses: actions/cache@v3
        with:
          path: .downloaded-cache
          key: dl-cache-win-mswin-${{ hashFiles('src/gems/bundled_gems') }}

      - name: build & install
        timeout-minutes: 30
        run:  ./1_0_mswin.ps1

      - name: test
        timeout-minutes: 70
        run:  ./2_0_test.ps1
        env:
          APPVEYOR: 'True'

      - name: CLI Check Bash
        shell: bash
        run: ./cli_test_bash

      - name: upload asset
        timeout-minutes: 5
        uses: ./.github/actions/upload-binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ruby_path: ./${{ env.RL_DIR }}

      - name: save log artifact
        if: success() || failure()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_LOGS }}
          path: ./logs
