name: mswin
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  mswin:
    strategy:
      matrix:
        vs: [2022]
      fail-fast: false
    runs-on: windows-${{ matrix.vs }}
    env:
      PRE: ruby-mswin

    steps:
      - name: git config
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: Update VS Build Tools
        run: |
          Invoke-WebRequest https://aka.ms/vs/17/release/vs_Enterprise.exe -OutFile C:/vs_Enterprise.exe
          C:/vs_Enterprise.exe updateall --quiet --includeOptional --wait --clean
          &"C:/Program Files (x86)/Microsoft Visual Studio/Installer/setup.exe" updateall --quiet

      - name: VS Where
        run: |
          &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
