name: mswin
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  mswin:
    strategy:
      matrix:
        vs: [2025]
      fail-fast: false
    runs-on: windows-${{ matrix.vs }}
    env:
      PRE: ruby-mswin

    steps:
      - name: git config
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: repo checkout
        uses: actions/checkout@v4

      - name: VS prep
        run: |
          Invoke-WebRequest https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/updt/2025/06/visualstudioupdate-17.0.0to17.14.4-online_fd647d1ea50c860c88eaedbc446d8c92a6d173cf.exe  -OutFile C:/vs_17.14.4.exe
          Invoke-WebRequest https://aka.ms/vs/17/release/vs_Enterprise.exe -OutFile C:/vs_Enterprise.exe
          Get-ItemProperty -Path C:/vs_Enterprise.exe | Format-List
          C:/vs_17.14.4.exe

      - name: Update VS Build Tools
        run: ./UpdateVS.ps1 -RunAsAdmin

      - name: VS Where
        run: |
          &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
